---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: centos-6.5
  - name: centos-5.10
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4
  - name: debian-6.0.8

suites:
- name: default
  run_list:
    - recipe[up2date]
    - recipe[vsftpd]
  attributes:
    vsftpd:
      config:
        listen_address: 127.0.0.1
      allowed:
        - vagrant
